### ISSUE TITLE
Click on text not working

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#102]
_From [glenview...@gmail.com](https://code.google.com/u/110087215095127878251/) on October 15, 2010 21:46:13_

I've been using Robotium now quite successfully to run around 30 different solo method calls in various tests.  I was using 1.7.1, and tried the new 1.8.0, as well as the suggestions to modify the manifest.  Nothing changes this behavior.  

I'm having some trouble coaxing it to click a textview though.  It's a nested view structure with a scrollview that has a textview and a bunch of buttons inside.

I tried solo.clickOnText(".*Show.*") but Solo responds that it couldn't find the text even though it's clearly there on screen.  I even stepped through the test to confirm.

I tried then using clickOnScreen as a kludge.  It clicked on the screen and enabled the buttons; however then, the clickOnButton method exhibited the same behavior. 

By the way, it would be nice if you posted a snapshot of the source to the downloads from now on with each version so I don't have to use git and try to figure out which is the right source version.  That way I can try to debug it myself.

Thanks!

_Original issue: http://code.google.com/p/robotium/issues/detail?id=23_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 16, 2010 05:23:25_

What happens if you do something like this:

for (TextView textView : solo.getCurrentTextViews())
Log.d("Robotium_TAG", "textView: " + textView.getText());

Do you see the text view displaying "show" in the log?

**Owner:** renasreda

**Comment by renas** [comment]
_From [glenview...@gmail.com](https://code.google.com/u/110087215095127878251/) on October 16, 2010 14:37:22_

Thanks for following up so quickly.  Strangely, only the top textview is returned when executing that code.  The views are laid out as follow (simplified for reading)

\<LinearLayout 
    \<LinearLayout 
        \<ScrollView
            \<TextView />
        \</ScrollView>
    \</LinearLayout>
    \<LinearLayout
        android:id="@+id/horizontalLine"/>
    \<LinearLayout 
        \<ScrollView
            \<TextView />
        \</ScrollView>
    \</LinearLayout>
    \<LinearLayout />
\</LinearLayout>

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 16, 2010 15:02:31_

Interesting. If they are shown on the screen then you should have access to them. Would it be possible for you to send me this application or one that displays this problem?

**Comment by renas** [comment]
_From [buildone...@gmail.com](https://code.google.com/u/106751982668500197055/) on October 20, 2010 01:29:01_

I also had the same problem.I used method clickOnText() click on textview in single
choice dialog.but it can't be selected.

**Comment by renas** [comment]
_From [jegan.k...@gmail.com](https://code.google.com/u/111142036555787391759/) on October 22, 2010 03:17:51_

I also faced this problem ... I have two image button . In the middle i have text view ...Its clearly visible and it able to search the test also .. but it is not clickable ... My textview has  text and background image property .

**Comment by renas** [comment]
_From [glenview...@gmail.com](https://code.google.com/u/110087215095127878251/) on October 22, 2010 06:06:15_

@renasreda: Sorry, but I haven't been able to spend the time to narrow this down to a small example for you.  I'll see what I can do.  Have you by any chance tried constructing a similar view to see if you can reproduce the problem?

Thanks for all of your work!

**Comment by renas** [comment]
_From [jegan.k...@gmail.com](https://code.google.com/u/111142036555787391759/) on October 26, 2010 04:30:16_

I am getting this below error :

junit.framework.assertionfailederror: View is not visible and can therefore not be clicked 
in robotium file :
clicker.clickonscreen(clicker.java:152)
clicker.clickontext(clicker.java:285)
Solo.clicklongontext(clicker.java:717) ...

sorry ,i cant paste the full error code ,as it was exectued in test PC .

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 26, 2010 07:32:46_

Jegan your error is different. The reason for your problem is that you are trying to click on a text view that is not visible on the screen. Probably you have two text views displaying the same text were only one is visible. Use clickLongOnText(String text, int match) instead. Where the match would be 2 or possibly higher depending on how many text views you have that display the same text.

**Comment by renas** [comment]
_From [albert.a...@gmail.com](https://code.google.com/u/106493348201453925831/) on October 28, 2010 00:11:46_

I am having similar problem.  I'm trying to click on text that is in a spinner list, and the logs show that Robotium cannot find the item on the list.  It seems if there is only alpha number characters, clickOnText works. But if there is non alpha number, it doesn't. 

I'm trying to step thru a spinner list with the following items..

None (PCM)
PCMA
AMR (6.50 kbps)
AMR (14.25 kbps)

PCMA is the only item on the list that will work with ClickOnText. All the rest do not work.  I've had examples where spaces were in text items, so maybe it's the other characters that are making the method not work?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 30, 2010 02:14:16_

Albert, the reason for your problem is that ( and ) are interoperated as regular expressions. Use // before the ( and ).

**Comment by renas** [comment]
_From [glenview...@gmail.com](https://code.google.com/u/110087215095127878251/) on October 30, 2010 06:13:13_

I believe renasreda means \\, (two back slashes, not forward slashes.)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on October 30, 2010 07:14:38_

Sorry about that, it should be two back slashes. Thanks for that Jeff.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 12, 2010 11:08:19_

Hi Jeff,

I am not able to reproduce this problem. If you can not send me an app that displays this problem then I will have to close this issue.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 14, 2010 11:12:30_

Not reproducable therefor will be closed.

**Status:** WontFix

**Comment by renas** [comment]
_From [castigliafrancesco](https://code.google.com/u/castigliafrancesco/) on November 28, 2011 09:51:14_

Hi 
Sorry for my english. I'm Italian. Could you tell me how select a not visible spinner on the screen with robotium?

The spinner isn't in focus. It's clickable but not visible because it's out the screen.

Thanks

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 29, 2011 00:20:32_

To be able to click it needs to be shown on the screen.

**Comment by renas** [comment]
_From [nrv1...@gmail.com](https://code.google.com/u/113552217573721364177/) on November 21, 2012 23:37:28_

Hi reanasreda
I am having the same issue too, I see my text right in front of me and my test is not able to click it, i tried using ClickLongonText but that didn;t work too.
I thought of using an assertTrue method and check if I can search for that text and that case failed too...

I keep getting the assertionFailed error.
Any help is appreciated

Vivek

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 21, 2012 23:42:31_

@Vivek, The activity needs to belong to the same process as the app under test.

**Comment by vitrinh282** [comment]
clickonscreen not working on framework view from github like twowayview , viewpager , .....
