### ISSUE TITLE
Missing clickOnImageButton(int id)

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#208]
_From [aried3r](https://code.google.com/u/aried3r/) on July 22, 2011 06:07:05_

What steps will reproduce the problem? clickOnImageButton() only takes an index, not and R.id. What version of the product are you using? On what operating system? Robotium 2.4, any OS Please provide any additional information below. It would be useful to have a method to click on an ImageButton based on its ID rather than just its index which might change over time when you restructure the UI.

At the moment, we use something like this:
int i = 0;
for (ImageButton imageButton : solo.getCurrentImageButtons()) {
	if (imageButton.getId() == imageButtonId) {
		solo.clickOnImageButton(i);
		break;
	}
	++i;
}

_Original issue: http://code.google.com/p/robotium/issues/detail?id=129_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 24, 2011 08:12:26_

You can do the following:

ImageButton imageButton = (Image) solo.getView(R.id.of.imagebutton);

solo.clickOnView(imageButton);

**Status:** Invalid

**Comment by renas** [comment]
_From [aried3r](https://code.google.com/u/aried3r/) on July 26, 2011 08:11:25_

Sometimes the emulator is too slow, so when I call solo.getView(R.id.of.imagebutton) it will return null. I had to add a solo.sleep(1000) before it, which isn't always enough. It also seems silly to me, of putting solo.sleep() everywhere just to make the code more reliable.
With the - not so clean - method of using the loop I never encountered this issue, because solo.getCurrentImageButtons() always returned all of the ImageButtons.

Is there no cleaner _and_ more reliable method of using the loop? Because I will probably revert to using the loop if there is not.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 26, 2011 08:39:16_

I agree, using sleeps is not a good solution. Try this:

solo.waitForView(ImageButton.class);
ImageButton imageButton = (Image) solo.getView(R.id.of.imagebutton);

solo.clickOnView(imageButton);

If you want to be even more specific you can use:

solo.waitForView(final Class<T> viewClass, final int minimumNumberOfMatches, final int timeout)

**Comment by renas** [comment]
_From [aried3r](https://code.google.com/u/aried3r/) on July 29, 2011 14:03:17_

Thank you. This worked out nicely.

**Comment by renas** [comment]
_From [glamour....@gmail.com](https://code.google.com/u/118006805662722538912/) on February 23, 2014 00:24:57_

I wrote that within my code to click on an image button ...

solo.waitForView(ImageButton.class);
ImageButton imageButton = (ImageButton) solo.getView("com.softxpert.sds.R.id.addFolderAction");
solo.clickOnView(imageButton);

BUT, It doesn't work and here's the error .. any help ?

junit.framework.AssertionFailedError: View with id: 'com.softxpert.sds.R.id.addFolderAction' is not found!
at com.robotium.solo.Solo.getView(Solo.java:1990)
at com.robotium.solo.Solo.getView(Solo.java:1970)
at com.example.android.apis.test.test.AddIconTest3.testRecorded(AddIconTest3.java:57)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1575)

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 23, 2014 06:28:21_

Try to use this as the I'd string instead: addFolderA

**Comment by alexEWR** [comment]
But what to do if you do blackBox testing and doesn't have sources?

**Comment by renas** [comment]
clickOnImageButton(int index) takes an index and not the ID. Try
clickOnImageButton(0) and you will see. If you want to click on a view with
a specified ID you can use clickOnView(solo.getView(r.id.x))

**Comment by alexEWR** [comment]
How I can use 
`clickOnView(solo.getView(r.id.x))`
if I have not sources?

**Comment by renas** [comment]
You can use solo.getView(String resourceID). The resource ID you can find
out through uiautomatorviewer.
