### ISSUE TITLE
assertCurrentActivity() doesn't work on ICS

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#304]
_From [Xavier.B...@gmail.com](https://code.google.com/u/109284507300599517250/) on February 08, 2012 05:44:26_

What steps will reproduce the problem? 1. Create an Activity A with a button which launch another Activity B
2. In the test case start Activity A and click on the button.
3. Sleep for 5 seconds (to allow the activity to be launch)
4. Then do assertCurrentActivity(B.class) What is the expected output? What do you see instead? The assertCurrentActivity fail. It says that the current activity is A whereas the activity B is launched. What version of the product are you using? On what operating system? I'm using the latest version of Robotium (3.1) on a Samsung Nexus S (Android 4.0.3). Please provide any additional information below. I tested the same test on another versions of Android (HTC Vision with 2.3.3 and emulator with 2.1) and it works.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=225_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 08, 2012 08:17:59_

Please try it on the emulator.

**Comment by renas** [comment]
_From [ebelets...@gmail.com](https://code.google.com/u/115782632646421861665/) on February 09, 2012 09:46:20_

am experiencing the same problem on 4.0.3

**Comment by renas** [comment]
_From [Xavier.B...@gmail.com](https://code.google.com/u/109284507300599517250/) on February 09, 2012 14:19:35_

Well, this is weird. I did a simple test case to reproduce the bug and it works on the emulator. I'll try tomorrow on the phone this simple test.

**Comment by renas** [comment]
_From [Xavier.B...@gmail.com](https://code.google.com/u/109284507300599517250/) on February 10, 2012 00:15:55_

I tested my simple test case on the Nexus S and it worked... I guess I have a problem with my complexe test case...
I think you can close the issue.

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 10, 2012 02:05:22_

**Status:** Invalid

**Comment by renas** [comment]
_From [salvetti...@gmail.com](https://code.google.com/u/109242612347519492627/) on February 10, 2012 07:38:45_

I'm have the same problem, using an AVD with 4.0.3 , when I run complex test scenarios, and the problems is where I use the solo.assertCurrentActivity("Asserting " + activityClass.getSimpleName(), activityClass);   , the current Activity is not update, stay in the last Activy . Using the names of the first post, the current Activy, for Robotium is 'Activity A', but the app is running the 'Activity B'.

I using and AVD with 1024 Mib and SDK 4.0.3 , and the last Robotium version 3.1. I tested the same test on HTC Nexus One, with 2.3.4 and emulator with 2.1 , 2.2, and 2.3.

thanks for your help.
Mariano Salvetti

**Comment by renas** [comment]
_From [yangdong...@gmail.com](https://code.google.com/u/108538885313772993141/) on July 18, 2012 01:56:17_

I did a simple test case to reproduce the bug and it works on the emulator. I'll try tomorrow on the phone this simple test.

**Comment by renas** [comment]
_From [spiritch...@gmail.com](https://code.google.com/u/115182257512156424972/) on September 01, 2012 02:07:00_

I have a same issue:
reproduce problem：
1、I have a button in Activity A ,when click it will do follow:
Intent intent = new Intent();
intent.setAction(Intent.ACTION_VIEW);
intent.setData(Uri.parse(url));
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
mContext.startActivity(intent);

2、when solo.clickOnButton , I can see chrome come out and loading the url to websit.

3、solo.assertCurrentActivity() still is the Activity A.

expected output should be the chrome activity .

**Comment by renas** [comment]
_From [spiritch...@gmail.com](https://code.google.com/u/115182257512156424972/) on September 01, 2012 02:08:27_

I have try it in emulator sdk 2.1 and my phone 4.1.1 , same problem!

**Comment by renas** [comment]
_From [amitbarv...@gmail.com](https://code.google.com/u/112407128677152872324/) on October 17, 2014 02:12:33_

I have face the same problem while launching the activity on emulator.

**Comment by mimers** [comment]
Same problem on Android 6.0.1 Nexus 5
