### ISSUE TITLE
solo.clickOnWebElement() does not work

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#488]
_From [bolt...@gmail.com](https://code.google.com/u/108059710326203293533/) on March 07, 2013 17:49:56_

I am trying to test a Hybrid app on Android.
This is a Hybrid app built by PhoneGap, it packages the Sencha Touch example web app: http://dev.sencha.com/deploy/touch/examples/production This is the testing code:

By byKitchensink = By.xpath(“//a[./img[@src='kitchensink/resources/icons/icon.png']]”);
solo.waitForWebElement(byKitchensink, 60000, false);
solo.clickOnWebElement(byKitchensink, 0, false);
Log.d(getName(), “Clicked Kitchensink”);
By byUserInterface = By.xpath(“//div[./span[text()='User Interface']]”);
solo.waitForWebElement(byUserInterface, 60000, false);
solo.clickOnWebElement(byUserInterface, 0, false);

But the click action does not work:
solo.clickOnWebElement(byKitchensink, 0, false);

I am sure the xpath “By” can be found, because it works, and, if I click the Web Element manually, the downstream steps work well.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=409_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 07, 2013 20:47:50_

Thanks for reporting this. Would it be possible for you to send me your application?

**Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [bolt...@gmail.com](https://code.google.com/u/108059710326203293533/) on March 10, 2013 18:05:50_

Yes, sure. Thank you in advance.

**Attachment:** [SampleProject.zip](http://code.google.com/p/robotium/issues/detail?id=409#hc2)

**Comment by renas** [comment]
_From [bolt...@gmail.com](https://code.google.com/u/108059710326203293533/) on March 10, 2013 18:08:44_

And, this is my test code:

package com.ca.test.test;

import android.test.ActivityInstrumentationTestCase2;
import android.util.Log;

import com.ca.test.SampleProject;
import com.jayway.android.robotium.solo.By;
import com.jayway.android.robotium.solo.Solo;
import com.jayway.android.robotium.solo.WebElement;

public class SampleProjectTest extends ActivityInstrumentationTestCase2<SampleProject> {
	
	private Solo solo;

	public SampleProjectTest() {
		super(SampleProject.class);
	}
	
	@Override
	public void setUp() throws Exception {
		//setUp() is run before a test case is started. 
		//This is where the solo object is created.
		solo = new Solo(getInstrumentation(), getActivity());
	}
	
	@Override
	public void tearDown() throws Exception {
		//tearDown() is run after a test case has finished. 
		//finishOpenedActivities() will finish all the activities that have been opened during the test execution.
		solo.finishOpenedActivities();
	}
	
	public void testSample() throws Exception {
		By byKitchensink = By.xpath("//a[./img[@src='kitchensink/resources/icons/icon.png']]");
		solo.waitForWebElement(byKitchensink, 60000, false);
		solo.clickOnWebElement(byKitchensink, 0, false);
		Log.d(getName(), "Clicked Kitchensink");
		By byUserInterface = By.xpath("//div[./span[text()='User Interface']]");
		solo.waitForWebElement(byUserInterface, 60000, false);
		solo.clickOnWebElement(byUserInterface, 0, false);
	}

}

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 11, 2013 02:38:50_

It seems as if your issue is due to wrong xpath string. When I try this it works:

By byKitchensink = By.xpath("/html/body/div/section/ul/li/a/img");

Also, you can use by.textContent("Kitchen Sink");

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on March 11, 2013 02:55:49_

Please let me know if you experience more issues while testing the web support.

**Status:** Invalid

**Comment by renas** [comment]
_From [bolt...@gmail.com](https://code.google.com/u/108059710326203293533/) on March 13, 2013 19:43:15_

I changed my test code to this:

public void testSample() throws Exception {
	By byKitchensink = By.xpath("//a[./img[@src='kitchensink/resources/icons/icon.png']]");

	long t0 = System.currentTimeMillis();
	solo.waitForWebElement(byKitchensink, 60000, false);
	long t1 = System.currentTimeMillis();
	Log.d(getName(), "Waited " + (t1 - t0) + " ms for byKitchensink");

	solo.clickOnWebElement(byKitchensink, 0, false);
	Log.d(getName(), "Clicked Kitchensink");
	By byUserInterface = By.xpath("//div[./span[text()='User Interface']]");

	t0 = System.currentTimeMillis();
	solo.waitForWebElement(byUserInterface, 60000, false);
	t1 = System.currentTimeMillis();
	Log.d(getName(), "Waited " + (t1 - t0) + " ms for byUserInterface");

	solo.clickOnWebElement(byUserInterface, 0, false);
}

I got the log message:
	Waited 2174 ms for byKitchensink
	Waited 60315 ms for byUserInterface

So, it shows the xpath is found, and, code "solo.clickOnWebElement(byKitchensink, 0, false);" passed, it also shows the xpath is found.

If the xpath is not found, "solo.clickOnWebElement(byKitchensink, 0, false);" will throw exception, but, it did not.
The exception is thrown from the last row: "solo.clickOnWebElement(byUserInterface, 0, false);".

So, I do not think this issue is caused that the first xpath is not found.

How do you think of that?

**Comment by domy18** [comment]
Hi whats the problem?
  //carichiamo la webview dentro il layout specificato
        mWebView = (WebView) findViewById(R.id.webView);
        mWebView.getSettings().setJavaScriptEnabled(true);
        mWebView.getSettings().setLoadsImagesAutomatically(true);
        //carichiamo finalmete la url
        mWebView.setWebViewClient(new WebViewClient());
        mWebView.loadUrl(url);




        }


    @Override
    protected void onResume() {
        super.onResume();
        // If we didn't have any trouble retrieving the data, it is now
        // time to get at the stuff.

        solo.clickOnWebElement(By.textContent("All"));

        solo.sleep(50000);

    }
thank
