### ISSUE TITLE
soloSearchText() doesn't work correctly.

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#568]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on July 19, 2013 01:59:44_

I'm having a problem with searchText() function used with Robotium.

I'm searching for this string:

\<string name="provisioning_wizard_title_2">Service Activation Wizard (Step 2)</string>

I defined it in string xml, and I'm searching it this way:

Activity act=solo.getCurrentActivity(); 
String string = solo.getString(act.getResources().getIdentifier(stringId, "string", act.getPackageName()));

It fails when I call

assertTrue(solo.searchText(provisioning_wizard_title_2));

and it fails also if i call:

assertTrue(solo.searchText("Service Activation Wizard (Step 2)"));
even if that is the string I'm seeing in the focused screen activity.

The strange thing is that it works if I use the same string without last character:

assertTrue(solo.searchText("Service Activation Wizard (Step 2"));

and it works if I use

assertTrue(solo.searchText(string.substring(0, string.length()-1)));

I hope someone could help me.

Sorry for my english!

Thank you.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=489_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 19, 2013 03:59:41_

Due to regex support in searchText() some characters will trigger it. Use Pattern.quote(string) example: Pattern.qoute("provisioning_wizard_title_2")

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on July 19, 2013 05:16:22_

Thanks! It works!!! :)

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on July 22, 2013 08:47:16_

I'm having the same problem with this string:
\<string name="terms_and_conditions_title">Terms &amp; Conditions</string>

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 23, 2013 01:54:23_

Does searchText("Terms") work?

**Comment by renas** [comment]
_From [flavioca...@gmail.com](https://code.google.com/u/107380997665066938982/) on July 23, 2013 01:59:45_

Thank for answering.
Yes It works with that string but now it's not working with another string:

\<string name="end_wizard_text">
    Service activation wizard is almost complete. Press \'Done\' button to
activate MDP Client.
\</string>

I'm calling it from Robium test class as follow:

Activity act=solo.getCurrentActivity();
String s =
solo.getString(act.getResources().getIdentifier("end_wizard_text",
"string", act.getPackageName()));
return Pattern.quote(s);
assertTrue("End activation screen expected.",
solo.searchText(Pattern.quote(s)));

But it never fails; If i test this on a different layout it
solo.searchText() keeps on returning true even if I don't have that text on
the screen.

Thank you!

Flavio Capaccio - (+39) 3928925046

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on July 23, 2013 02:02:23_

Then you need to use public boolean searchText(String text, boolean onlyVisible) as the view is still there but hidden. Setting onlyVisible to true will only search for visible views. Please see the javadoc for more information. https://code.google.com/p/robotium/wiki/RobotiumAPIDocumentation

**Comment by leonardonogueira** [comment]
What if i want to search for an exact string?
For example, i have a label with text "Invite", when i perform searchText("Invite"), it returns true.
If i change the label to "Invites", the searchText("Invite") still returns true. What can i do to the method return false in this case?

**Comment by renas** [comment]
All the search and waitFor methods support regular expression. You can use regular expression for your purpose.
