### ISSUE TITLE
I am unable to test application via apk file getting the error when we resign apk by jarsigner

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#590]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 05, 2013 00:44:51_

Hi Sir,

1--I Follow all this below given procedure signed procedure done           successfully 
    but when we install this apk it not to be install it given the error
    apk installation failed:INSTALL_FAILED_INVALID_APK.

2--  and also i used your resign tool it sign the apk and it is install on 
     device but unable to test full application after testing few activity
      it throw the exception FileNotFindException.

So please sir help me.

Procedure--

*    Un-zip the apk file
*   Delete the META-¬INF folder
*   Re-zip the apk file
It will zip file as "applicationName.apk.zip" , rename it and make it as "applicationName.apk"
* In Dos prompt/Terminal write following commands
\> jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android applicationName.apk
androiddebugkey

\>zipalign 4 applicationName.apk TempApplicationName.apk

Thanks & Regrads

Saurabh Shukla

_Original issue: http://code.google.com/p/robotium/issues/detail?id=511_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on September 05, 2013 20:56:32_

As you can succesfully run your tests using 2 it means that the signature is not the mistake. Seems to be a bug in the app you are testing.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 10, 2013 03:06:21_

Hi Sir,

My app working file but when i resign the the apk by resign tool after that apk file not working. please sir help me.

Thanks

Saurabh

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on September 10, 2013 03:39:40_

You should try to resign it manually instead. The resign tool has not been created by us.

**Comment by renas** [comment]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 10, 2013 05:02:56_

Hi Sir,

I have also try to resign apk manually using below given procedure and it resign 
successfully but when i install this apk on device (Mobile)  it given the error
    apk installation failed:INSTALL_FAILED_INVALID_APK. so please sir help me.


Procedure--

*    Un-zip the apk file
*   Delete the META-¬INF folder
*   Re-zip the apk file
It will zip file as "applicationName.apk.zip" , rename it and make it as "applicationName.apk"
* In Dos prompt/Terminal write following commands
\> jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android applicationName.apk
androiddebugkey

\>zipalign 4 applicationName.apk TempApplicationName.apk



Thanks
Saurabh Shukla

**Comment by renas** [comment]
_From [luckynav...@gmail.com](https://code.google.com/u/116571443419374630832/) on September 10, 2013 05:08:37_

what is the java version installed ?

**Comment by renas** [comment]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 10, 2013 05:16:01_

Hi Sir,

JDK 7.

**Comment by renas** [comment]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 10, 2013 05:18:56_

Hi sir,

I am trying to install both jdk 6 and 7 one by one and follow the both of different procedure and apk resign successfully it thrown the same error  
  apk installation failed:INSTALL_FAILED_INVALID_APK  on both cases.

Thanks

Saurabh

**Comment by renas** [comment]
_From [luckynav...@gmail.com](https://code.google.com/u/116571443419374630832/) on September 10, 2013 05:23:26_

In case of Java7 you should re-sign manually & there is also a note in the tutorial about java7. 

For java 7 please use following command instead,
\> jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android ­sigalg MD5withRSA
­digestalg SHA1 applicationName.apk androiddebugkey

Please use above command, rest will be same.

**Comment by renas** [comment]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 10, 2013 05:29:21_

Hi sir,

I have also used  this command for java 7. apk resign successfully but it thrown the same error  
  apk installation failed:INSTALL_FAILED_INVALID_APK  on both cases.

Thanks

saurabh shukla

**Comment by renas** [comment]
_From [luckynav...@gmail.com](https://code.google.com/u/116571443419374630832/) on September 10, 2013 05:35:52_

please follow the steps completely, it works. 

Procedure--

*    Un-zip the apk file
*   Delete the META-¬INF folder
*   Re-zip the apk file
It will zip file as "applicationName.apk.zip" , rename it and make it as 
"applicationName.apk"
* In Dos prompt/Terminal write following commands
\> jarsigner -keystore ~/.android/debug.keystore -storepass android -keypass android ­sigalg MD5withRSA ­digestalg SHA1 applicationName.apk androiddebugkey
\>zipalign 4 applicationName.apk TempApplicationName.apk

**Comment by renas** [comment]
_From [shuklasa...@gmail.com](https://code.google.com/u/107968646859034667637/) on September 10, 2013 05:45:42_

Hi Sir,
 sir i  told you i follow all  these steps completely, and generated signed apk 
successfully but re-signed apk not works.

Thanks
Saurabh

**Comment by renas** [comment]
_From [luckynav...@gmail.com](https://code.google.com/u/116571443419374630832/) on September 10, 2013 06:19:00_

I just did the same, it worked fine with me

**Comment by UserAutomation** [comment]
i am trying to run robotium on mac and getting the resign error. i have latest jdk. please tell how to fix it ?
