### ISSUE TITLE
junit.framework.AssertionFailedError: EditText is not found!

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#601]
_From [Sameena....@gmail.com](https://code.google.com/u/104357694913142239122/) on September 24, 2013 06:24:33_

What steps will reproduce the problem? 1.Launch the emulator.
2.Execute the test cases->Run as Junit Test case.
3.App home screen is displayed.But Assertion failed error is displayed for Text fields and Check boxes. What is the expected output? What do you see instead? Expected Result:Navigates to Next Screen of the app.
Actual Result: junit.framework.AssertionFailedError: EditText is not found! What version of the product are you using? On what operating system? Robotium-solo-4.3,Windows 7,32bit Please provide any additional information below. Test Class:
package com.emd.test;
import com.jayway.android.robotium.solo.Solo;

import android.test.ActivityInstrumentationTestCase2;

@SuppressWarnings("unchecked")

public class Loginluck7 extends ActivityInstrumentationTestCase2 {
	
	private static final String LAUNCHER_ACTIVITY_FULL_CLASSNAME="com.ncr.emd.Emd";
	private static Class launcherActivityClass;
	static{
		try{
				launcherActivityClass = Class.forName(LAUNCHER_ACTIVITY_FULL_CLASSNAME);
			} 
			
			catch (ClassNotFoundException e)
			
			{
					throw new RuntimeException(e); 
			} 
		}
	public Loginluck7() 
	{
		super(launcherActivityClass);
		
		// TODO Auto-generated constructor stub
	}
	

	
	
	private Solo solo;
	protected void setUp() throws Exception {
	    super.setUp();
	    solo = new Solo(getInstrumentation(), getActivity());
	    
	}
	
	
	public void test_1_Rememberme()
	{
		
		solo.waitForActivity(LAUNCHER_ACTIVITY_FULL_CLASSNAME);
		solo.enterText(0, "user");
		solo.enterText(1, "mobile");
		solo.enterText(2, "password5");
		solo.clickOnButton("Submit");
		solo.waitForText("Deposits");
	}
	
	

	public void tearDown() throws Exception
	{
		solo.finishOpenedActivities();
	}

}

AndroidManifest.xml:
\<?xml version="1.0" encoding="utf-8"?>
\<manifest xmlns:android=" http://schemas.android.com/apk/res/android "
    package="com.emd.test"
    android:versionCode="1"
    android:versionName="1.0" >

    \<uses-sdk android:minSdkVersion="10" 
        	android:targetSdkVersion="17"/>
    \<uses-permission android:name="android.permission.INTERNET"></uses-permission>
      \<supports-screens android:anyDensity="true"/>
    

    \<instrumentation
        android:name="android.test.InstrumentationTestRunner"
        android:targetPackage="com.emd.Emd" />
    
  
    \<application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name" >
        \<uses-library android:name="android.test.runner" />
    \</application>

\</manifest>

We have only apk file

Thanks,
Sameena

_Original issue: http://code.google.com/p/robotium/issues/detail?id=522_

**Comment by renas** [comment]
_From [Sameena....@gmail.com](https://code.google.com/u/104357694913142239122/) on September 25, 2013 05:12:32_

Hi All,

Below are the errors displayed in Logcat when i tried to run the test script.

09-25 17:29:06.874: E/dalvikvm(1488): Could not find class 'android.support.v4.app.FragmentActivity', referenced from method com.jayway.android.robotium.solo.Waiter.getSupportFragment

09-25 17:29:06.934: E/dalvikvm(1488): Could not find class '[Landroid.view.MotionEvent$PointerProperties;', referenced from method com.jayway.android.robotium.solo.Zoomer.generateZoomGesture

09-25 17:29:06.944: E/dalvikvm(1488): Could not find class '[Landroid.view.MotionEvent$PointerProperties;', referenced from method com.jayway.android.robotium.solo.Swiper.generateSwipeGesture

09-25 17:29:06.944: E/dalvikvm(1488): Could not find class '[Landroid.view.MotionEvent$PointerProperties;', referenced from method com.jayway.android.robotium.solo.Tapper.generateTapGesture

09-25 17:29:06.964: E/dalvikvm(1488): Could not find class '[Landroid.view.MotionEvent$PointerProperties;', referenced from method com.jayway.android.robotium.solo.Rotator.generateRotateGesture.

Could you please help me.

Thanks & Regards,
Sameena

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on September 26, 2013 11:58:22_

The view is not an EditText. Use hierarchyviewer to see the views that your app displays.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [Tlakh...@gmail.com](https://code.google.com/u/109575906032784442151/) on October 21, 2013 07:55:57_

Hi Renas,

I am also getting this error. What does it mean and how to deal with it?
How to use hierarchyviewer ??

**Comment by PrabhatPandey** [comment]
@renas following article will help you in this regard
http://code.tutsplus.com/tutorials/android-tools-using-the-hierarchy-viewer--mobile-6997
