### ISSUE TITLE
Cannot read content of multiple webviews in the same activity

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#633]
_From [dvand...@gmail.com](https://code.google.com/u/101031171687721094056/) on November 13, 2013 14:39:47_

What steps will reproduce the problem? Robotium only supports working with the most recently created webview What is the expected output? What do you see instead? I'd like functionality to be able to specify the index of the webview that we want to work with.  I am testing an app that has multiple webviews in a single activity.

_Original issue: http://code.google.com/p/robotium/issues/detail?id=554_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on November 14, 2013 00:15:59_

Currently this is not something that we will prioritise. Depending on how many people show an interest in this it might change in the future. What you can do now is to first click on the web view you want to interact with to make it get focus.

**Status:** WontFix  
  **Owner:** renasr...@gmail.com

**Comment by fannahlin** [comment]
sometimes,  "click on the webview  want to interact with to make it get focus" can not solve the problem!
