### ISSUE TITLE
Screenshots do not get saved

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#658]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 06:38:50_

What steps will reproduce the problem? 1. Make sure target app has external write access
2. take screenshot 3. What is the expected output? What do you see instead? A screenshot in /mnt/sdcard/Robotium-Screenshots What version of the product are you using? On what operating system? 5.0.1 Please provide any additional information below. There is no error anywhere logged in logcat, test passes without problems.
The app under testing is visible when waiting before screenshot. I also tried with several different save paths in the Config file and PNG/JPG.
Nothing works, I can't get any output or error messages.

Relevant code:
solo.clickOnScreen(centerx, centery);
solo.sleep(1000);
solo.takeScreenshot();

_Original issue: http://code.google.com/p/robotium/issues/detail?id=579_

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 06:39:56_

public class ScreenshotsTaker extends ActivityInstrumentationTestCase2<PianoFragmentActivity> {

	private Solo solo;
	public ScreenshotsTaker() {
		super(PianoFragmentActivity.class);
	}

	@Override
	protected void setUp() throws Exception {		
	
		Config config = new Config();
//		config.screenshotFileType = ScreenshotFileType.PNG;
//		config.screenshotSavePath = Environment.getExternalStorageDirectory() + "/RobotiumTest/";
		solo = new Solo(getInstrumentation(), config);
		getActivity();
		super.setUp();
	}
	
	public void testTakeScreenshots() throws Exception
	{
		View scrollbarpiano = getActivity().findViewById(R.id.scrollbar_piano);
		int[] xy = new int[2];		
		scrollbarpiano.getLocationOnScreen(xy);
		int centerx = (scrollbarpiano.getWidth() / 2) + xy[0];
		int centery = (scrollbarpiano.getHeight() / 2) + xy[1];
		solo.clickOnScreen(centerx, centery);
		solo.sleep(1000);
		solo.takeScreenshot();
		
	}
}

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 06:41:23_

\<?xml version="1.0" encoding="utf-8"?>
\<manifest xmlns:android=" http://schemas.android.com/apk/res/android "
    package="***.test"
    android:versionCode="1"
    android:versionName="1.0" >

    \<uses-sdk android:minSdkVersion="8" />

    \<instrumentation
        android:name="android.test.InstrumentationTestRunner"
        android:targetPackage="***" />

    \<application
        android:icon="@drawable/ic_launcher"
        android:label="@string/app_name" >
        \<uses-library android:name="android.test.runner" />
    \</application>
    
    \<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
        

\</manifest>

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 06:41:46_

Target package has also android.permission.WRITE_EXTERNAL_STORAGE permission set.

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 06:58:11_

It looks like I finally got it working by disabling Hardware Acceleration in the target app. It looks like HW accel interferes with Robotium's ability to take screenshots. Is this a known issue?

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 07:10:51_

Unfortunately it still stops working after a few tries. Files just don't get saved.

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on February 23, 2014 07:22:15_

It turns out it is due to having the solo.takeScreenshot() method as last method in the testsuite. When I add a solo.sleep(1000) after the last screenshot call it saves ok, even with HW accel on. I guess it's due to threading issue, where the screenshots are taken on a thread, while the test finishes and kills the testrunner, taking the screenshot thread with it. Maybe handle this more properly?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on February 23, 2014 19:01:54_

Thanks for reporting this. Lets see what we can do to improve it.

**Status:** Accepted  
  **Owner:** renasr...@gmail.com

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 18, 2014 08:12:45_

Thanks again for reporting this. This has been fixed in Robotium 5.2.1.

**Status:** Verified

**Comment by renas** [comment]
_From [goo...@umito.nl](https://code.google.com/u/110284431970829714410/) on June 18, 2014 11:53:59_

Ok, great! What was the solution?

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on June 18, 2014 21:35:53_

We lock the instrumentation thread until the screenshot thread has finished. Thus preventing what could happen previously.

**Comment by llucasapolinario** [comment]
I have the problem with android 7.1.1. The same program work correct in a similar device with android 6.0.1. Robotium solo 5.6.3.
