### ISSUE TITLE
solo.clickOnView(solo.getView(com.lgsi.test.R.id.buttonNoApk));

### ISSUE THREAD

**Issue by renas** [RobotiumTech/robotium#684]
_From [siba...@gmail.com](https://code.google.com/u/100552529535140677056/) on May 13, 2014 05:31:12_

What steps will reproduce the problem? error-java.lang.ClassCastException: com.lgsi.test.StartActivity cannot be cast to android.test.java.lang.ClassCastException: java.util.ArrayList cannot be cast to android.view.View[]

main error- java.util.ArrayList cannot be cast to android.view.View[] What is the expected output? What do you see instead? not able to click on the view(Button).should click on the view What version of the product are you using? On what operating system? windows-7.robotium-solo4.1 Please provide any additional information below. same code i have run long before but not its not running.
any solo.click is not working showing same error.
e.g- java.util.ArrayList cannot be cast to android.view.View[]

_Original issue: http://code.google.com/p/robotium/issues/detail?id=605_

**Comment by renas** [comment]
_From [renasr...@gmail.com](https://code.google.com/u/108052454046732184536/) on May 14, 2014 02:39:26_

Please update to Robotium 5.1.

**Status:** Invalid  
  **Owner:** renasr...@gmail.com

**Comment by jlhonora** [comment]
This still happens in Robotium 5.5.3. What I did was to assign the view to a specific variable instead of passing it inlined:

```
ImageButton sendButton = (ImageButton) solo.getView(R.id.some_id);
solo.clickOnView(sendButton);
```

I'm using gradle plugin version 2.0.0-alpha9, gradle 2.10
