### ISSUE TITLE
Need to add pressSoftKeyboardDoneButton and pressSoftKeyboardGoButton APIs

### ISSUE THREAD

**Issue by haitaoz** [RobotiumTech/robotium#775]
Robotium 5.4.1 has two APIs related to softkeyboard:

1. pressSoftKeyboardNextButton 
2. pressSoftKeyboardSearchButton

It is not enough since softkeyboard for EditText has another two action buttons:

1. Go
2. Done

Please add support for these two action buttons

**Comment by renas** [comment]
Thanks for the suggestion. We will add this in the next release.

**Comment by renas** [comment]
This has been integrated in Robotium 5.5.1
