### ISSUE TITLE
Sleep inside Waiter.waitForText method can be changed to wait and notitify

### ISSUE THREAD

**Issue by haitaoz** [RobotiumTech/robotium#776]
Understand UI has to wait till current search view operation return.

We could use wait(timeout) and notify to avoid the last sleep of 500ms on UI thread.

This can improve UI response time by 500ms maximum.

**Comment by renas** [comment]
Unfortunately the UI is slow therefor we have these sleeps to slow the execution down. Removing them will make the execution to fast which will lead to flaky tests.
