### ISSUE TITLE
Robitum is detecting the text which is hidden(Invisible) from android application.Is there a way to go check the visibility first and then search the text ?

### ISSUE THREAD

**Issue by PrabhatPandey** [RobotiumTech/robotium#778]
I used 
if(solo.searchText("DINNER")){
solo.clickOnText("DINNER");
assertTrue("XYZ")
}

I can see that in the whole screen the Text "DINNER" is not present infact developer told me that it is set Invisible in android application.

Robotium should not go inside the loop if the text is not visible on the screen. Any work around this ?

**Comment by renas** [comment]
All the search and waitFor methods have an "onlyVisible" parameter that can be set. Please see the javadoc for more information. 

http://robotium.googlecode.com/svn/doc/index.html
