### ISSUE TITLE
Taking Screenshot does not work on android M

### ISSUE THREAD

**Issue by daber** [RobotiumTech/robotium#779]
Tested on Android emulator x86 running Android 23 with google API.
Tested on Nexus 5 Running 6.0 build  MAP44I

Solo.takeScreenshot() - does not capture anything.

On Android 5 works correctly

**Comment by renas** [comment]
Thanks for reporting this.

**Comment by renas** [comment]
Its working for us. When we compile with API level 23 (compileSdkVersion 23) its working fine.

**Comment by renas** [comment]
We are able to reproduce this issue. Working on a fix.

**Comment by szprutamich** [comment]
Is it related to emulator, x86 or generally android 6.0?

**Comment by renas** [comment]
It's due to Android 6.0, a fix has been pushed.

**Comment by renas** [comment]
This has been fixed in Robotium 5.5.1
