### ISSUE TITLE
Robotium can't handle location service dialog

### ISSUE THREAD

**Issue by bio007** [RobotiumTech/robotium#780]
Hi, I have a problem with Robotium and location dialog from google play services. I would like to test a scenario when user has gps disabled. But when this dialog shows, Robotium can't detect it or even click on screen while it is shown - throwing java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission (adding this permission to manifest does not help).

Is there a way around this? Thanks.

![screenshot_20150922-090147](https://cloud.githubusercontent.com/assets/144213/10012912/de1c5542-610c-11e5-8e9b-9c9617d5bcff.png)

**Comment by renas** [comment]
Thanks for reporting this. Robotium uses the Android instrumentation framework and due to that its only allowed to interact with the app under test. The location dialog does not belong to your app and therefor the Android platform won't let you interact with it.
