### ISSUE TITLE
Robotium 5.5.1 List Condition failing

### ISSUE THREAD

**Issue by macgills** [RobotiumTech/robotium#781]
<code>private class WaitForListDeletion implements Condition
   {

```
  private final int initialCount;
  private final ListView view;

  public WaitForListDeletion(final ListView view)
  {
     this.view = view;
     initialCount = getCount(view);
  }

  private int getCount(final ListView view)
  {
     return view.getAdapter().getCount();
  }

  @Override
  public boolean isSatisfied()
  {
     return getCount(view) < initialCount;
  }
```

   }</code>
So I delete an item from a list (with a swipe gesture) and then use this condition.This condition no longer works and I really don't know why. Can not upgrade from 5.3.1.

**Comment by renas** [comment]
Thanks for reporting this. When you say it doesn't work how exactly doesn't
it work? Is this also the case with 5.4.1?

**Comment by macgills** [comment]
Thanks for speedy reply. I am asserting the result of the condition with a timeout of 20 seconds, probably overkill but the swipe triggers a DB transaction before the item is actually removed from the adapter. It passes on 5.3.1 in probably a second. Have not tried 5.4.1 but will do so now

**Comment by macgills** [comment]
Not working on 5.4.1

**Comment by renas** [comment]
Would it be possible for you to share your project or another project that
exhibits this issue?

**Comment by macgills** [comment]
I don't think it will become a priority at work for a while yet (no need for recyclerView methods immediately) so I can't justify the time to setting up a demo project, sorry. Definitely cannot share the project.

**Comment by renas** [comment]
Ok no worries. We'll see try to reproduce it on our side. Thanks again for
reporting this.

**Comment by macgills** [comment]
Project is dead? closing this to clear it out of my issues
