### ISSUE TITLE
"activityMonitorThread" thread leak -> activity leak -> OOM.

### ISSUE THREAD

**Issue by enikey87** [RobotiumTech/robotium#795]
Solo.finishOpenedActivities() doesn't correctly shutdown "activityMonitorThread".

This thread can prevent activities from being garbage collected causing OOM during large number of test execution (it can be reason of https://github.com/RobotiumTech/robotium/issues/706).

Thread hang caused by waitForActivity() call, that could wait forever cause of following execution chain:
- [InstrumentationThread]: finishOpenedActivities() -> finish activities ... execution planner interrupts us.
- [UiThread]: Activity.onDestroy().
- [ActivityMonitorThread]: waitForActivity() returns. waitForActivity() blocks again cause interruption flag still not set.
- [InstrumentationThread]:  finishOpenedActivities() resumes: interruption flag for ActivityMonitorThread = true. ... blabla. finishOpenedActivities() returns.

...

ActivityMonitorThread will wait forever preventing last activity it saw from being collected.

P.S.
Execution chain can be different cause I didn't run & debug it, but hang & leak caused by it is fact.

**Comment by renas** [comment]
Thanks for reporting this.
