### ISSUE TITLE
About Japanese document.

### ISSUE THREAD

**Issue by Maeno** [RobotiumTech/robotium#798]
Hi guys,

I'm Maeno.

Is there a japanese document in Robotium?
If none, I will translate English into Japanese.

How about that?

Best Regards,
MAENO.

**Comment by renas** [comment]
That would be great. Thanks for contributing.

**Comment by Maeno** [comment]
Thank you for your reply.

I will do my best. Please wait for some days.

**Comment by Maeno** [comment]
Hi, I will close this isse and the pull-req this weekends.
Are you OK?

Best Regards.

**Comment by renas** [comment]
Sorry about this Maeno. We will not have a possibility of maintaining this therefor its better if its not merged.

**Comment by Maeno** [comment]
Thank you for your reply.
I understand and agree with you.

I will close them tonight.
