### ISSUE TITLE
Recording Failed: java.lang.IncompatibleClassChangeError: org.apache.http.params.SyncBasicl

### ISSUE THREAD

**Issue by nayanapromax** [RobotiumTech/robotium#799]
While recording on Robotium Recorder, after selecting the apk and starting the recording, apk get installed on the device but after that below issue is coming

Recording Failed: java.lang.IncompatibleClassChangeError: org.apache.http.params.SyncBasicl

Details:

jdk 1.8.0_66

Android Studio 1.4.1

Robotium Recorder 2.2.7

Device: Intex Aqua Speed HD with android version 5.0

Kindly look in to the issue.

**Comment by renas** [comment]
The issue is due to the apk being obfuscated. Please make sure that the
org.apache library doesn't get obfuscated.

**Comment by nayanapromax** [comment]
Thanks so much for reply. I searched this issue and got some information
about it. Actually, this is an open issue and reproducible only on Android
5.0 (Lollipop) version. On Android 4.2.2 Jelly Bean, its working fine. I
will look into org.apache library and will check again for Android 5.0
Lollipop version. Thanks again for your support.

**Comment by nayanapromax** [comment]
Query: If this issue is due to obfuscated apk then should be reproducible
on other Android Versions too. Please clarify.
