### ISSUE TITLE
Can't deal with runtime permission of Marshmallow by robotium

### ISSUE THREAD

**Issue by thinking0** [RobotiumTech/robotium#803]
Hi,
from marshmallow (api level 23), is beginning runtime permission. so I tried to control the dialog. But it was failure.

could you let me know how to control runtime permission dialog by robotium?
 

thanks
dennis

**Comment by renas** [comment]
Would guess its not possible as the runtime permission dialog belongs to another application (thus not allowed to interact with it).

**Comment by PrabhatPandey** [comment]
@renas is there any work around to resolve this issue? If so please provide us some links so that we can resolve this issue ASAP.
