### ISSUE TITLE
Robotium Recorder failing to launch app on mobile device

### ISSUE THREAD

**Issue by asusZenfoneMy** [RobotiumTech/robotium#811]
I am getting this issue while launching the application on mobile device.
Test run failed: Instrumentation run failed due to 'java.lang.IncompatibleClassChangeError'

Can you suggest the steps to fix this issue??

**Comment by anomaly256** [comment]
Seeing this as well while evaluation robotium recorder before purchase.  It's a bit of a blocker to say the least.

recording failed: java.lang.incompatibleClassChangeError: org.apache.http.params.SyncBasicHttpParams

**Comment by renas** [comment]
This issue is due to obfuscation of the support package. Recording of obfuscated APK:s is perfectly fine. However the support package should be excluded from the obfuscation (its open source anyways so no need to obfuscate that piece of code).

**Comment by anomaly256** [comment]
In my case the package wasn't being obfuscated.  I found my specific issue shortly after posting here though, there was an include for an older version of robotium solo I missed and the older non-android httpcore/httpclient jars.  Removing those seems to have resolved the problem for me.
