### ISSUE TITLE
Gradle build-info.xml not found for module app

### ISSUE THREAD

**Issue by hannesa2** [RobotiumTech/robotium#822]
With
`classpath 'com.android.tools.build:gradle:2.0.0'`
I receive following error on first start

> Gradle build-info.xml not found for module app. Please make sure that you are using gradle plugin gradle:2.0.0-alpha4 or greater

the only thing to make it work again was to disable InstantRun in AS->Preferences->Build,Execution,Deployment->Instant Run->Enable Instant Run

**Comment by renas** [comment]
Thank you for reporting this.

**Comment by ChrisMukasa** [comment]
thanks hannesa2,i have the same error on android 2.1 on ubuntu 16.04, your commit save my day and my week, thanks a lot
