### ISSUE TITLE
Robotium Recorder failed

### ISSUE THREAD

**Issue by westito** [RobotiumTech/robotium#829]
Robotium recorder tries run gradlew, but my project not using it. I use gradle from separate gradle home dir. I can't set it to robotium recorder

> Input: 
>
>/Users/westito/Projects/gradlew -Dorg.gradle.daemon=true assembleDebug -b /Users/westito/Projects/Foosio/build.gradle 
>
>Output:

**Comment by renas** [comment]
At this moment we don't support that.
