### ISSUE TITLE
signing issue with Version 2.4.1

### ISSUE THREAD

**Issue by hannesa2** [RobotiumTech/robotium#836]
Today I upgraded in Android Studio to Robotium Recorder 2.4.1 plugin (I've a valid license)
But when I try to record a test with flavor **Debug** an error appear, ~/Robotium.log.txt show this

`/Users/hannes/git/tracks/code/executorproject/gradlew -Dorg.gradle.daemon=true assembleDebugAndroidTest -u -b /Users/hannes/git/tracks/code/executorproject/build.gradle`

with error 

`Keystore was tampered with, or password was incorrect`
but this seams not to be the error. When I look to generated (by Robotium) file

`/Users/hannes/git/tracks/code/executorproject/build.gradle`

> ```
>   signingConfigs {
>      debug {
>           storeFile file('/Users/hannes/git/release-key.keystore')
>      }
> ```

it has no information about password and alias !
In my _original_ build.gradle

> ```
> signingConfigs {
>     debug {
>         storePassword "android"
>         keyPassword "android"
>         keyAlias "androiddebugkey"
>     }
>     release {
>         keyAlias "release"
>         storeFile file('/Users/hannes/git/release-key.keystore')
>         storePassword 'mypass'
>         keyPassword 'mypass'
>     }
> ```

**So I see the bug that Robotium uses for flavor debug the wrong storeFile !**
This happen with new version ! Btw, please show us a changelog !

**Comment by renas** [comment]
Thanks for reporting this. We have not made any changes that could break
this. Probably this bug has existed for a while. We'll have a look at it.
