### ISSUE TITLE
Hang Up Phone Call With Robotium

### ISSUE THREAD

**Issue by jgarci40** [RobotiumTech/robotium#843]
Does Robotium provide a facility to click the hang up button during testing of a phone call? Thank you for your time and consideration.

**Comment by renas** [comment]
No, that is not possible.

**Comment by SKART1** [comment]
UI Automator may do this. [Here](https://medium.com/exploring-android/handling-android-runtime-permissions-in-ui-tests-981f9dc11a4e#.nthxvr9vz) is the article which describes how to click button "Allow/Deby" on new permission system of Android 6.X+ which as I understand similar to your case
