### ISSUE TITLE
getActivity() hangs when I run testcase.

### ISSUE THREAD

**Issue by heyyuyu** [RobotiumTech/robotium#846]
It will happend randomly when I run all test, getActivity() in public void setup() can't be runned. My LAUNCHER_ACTIVITY_FULL_CLASSNAME set as below :  

private static final String LAUNCHER_ACTIVITY_FULL_CLASSNAME = "com.app.ehang.copter.activitys.MainActivity";

**Comment by heyyuyu** [comment]
Use Thread to fix

**Comment by SKART1** [comment]
Can  you post your solution please?
