### ISSUE TITLE
BlackBox testing of Hybrid Apps

### ISSUE THREAD

**Issue by riganelli** [RobotiumTech/robotium#848]
I am trying to perform some automated tests on an hybrid app,  but I run into the ClassCastException "com.robotium.solo.RobotiumWebClient cannot be cast to org.apache.cordova.CordovaChromeClient".

Is there any limitation in testing Hybrid Apps? Is cordova supported by robotium?

**Comment by renas** [comment]
Robotium does not support Cordova.
