### ISSUE TITLE
Is Robotium dead?

### ISSUE THREAD

**Issue by aurora-anon** [RobotiumTech/robotium#874]
You haven't updated the project for 9 months

**Comment by renas** [comment]
Not dead, we're still maintaining it. If there are any issues please let us know.

**Comment by aurora-anon** [comment]
Not being constantly improved is like short death

**Comment by Salinn** [comment]
Hasn't been updated in 2 years, is this dead?

**Comment by Anlesvavor** [comment]
> Hasn't been updated in 2 years, is this dead?

I think now it is.
